engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    exclude_fingerprints:
    - 688dba3c94f5a9f053628299c1147c1b
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- test/
