# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
environment:
  - NPM_VERSION: 3.10.7
  - NPM_VERSION: 4

install:
  - npm install npm@$env:NPM_VERSION
  # Output useful info for debugging.
  - node --version
  - npm --version

build: off

test_script:
  - npm install
  - npm run build
  - npm run test
  - npm run e2e
